edge_arch: PartSR
client_arch: PartSR

gpu_id: 0 # Set a non-existent GPU ID to use CPU
ffmpeg: "ffmpeg" # "/home/yosame/Desktop/Grad_Proj/FFmpeg-Residual/ffmpeg"
ffmpeg_residual: "/home/yosame/Desktop/Grad_Proj/FFmpeg-Residual/ffmpeg_residual_3" # modified FFmpeg that supports MB-level residual exporting

source_server: "http://localhost:23333"
edge_port: 11451

edge_server: "http://172.22.5.108:11451"

video_width: 180
video_height: 320

classify_sample_rate: 10 # Use 1 frame in every x frames for GRU in classifier
classify_model_path: "models/classifier.pth"

beta: 1.8
dyn_thres: 6.6

sr_models: ["EDSR_S_x4_0.8799.pth"]
vsr_models: [false]
batch_size: [60] # for VSR models, set the clip length instead of the number of videos
pad: 5 # expand SR range to avoid edge effect
sr_sizes: [60, 90]